# When installind addtional plugins or extenstions dont forget to put them into
#requirement file
# pip freeze > requirements.txt

site_name: "" #Netomat SRL
site_url: https://www.netomat.io/
theme:
  name: material
  logo: assets/images/netomat_logo_gemini1b.png
  favicon: assets/images/favicon/favicon.ico
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  
nav:
  - Home: index.md
  - Services:
      - Overview: services/index.md
      - Architecture & Design: services/architecture_design.md
      - Engineering: services/engineering.md
      - Testing: services/testing.md
  - About: 
    - About me: about/me/about_me.md
    - Company Details: about/imprint.md
    # - Skills: about/me/skills.md
    # - Projects: about/me/projects.md
  - Blog: https://blog.netomat.io
  

plugins:
  - search
  - encriptmail:
       placeholderAt: (Q)
       placeholderDot: (P)
  - git-revision-date-localized:
      enable_creation_date: true
  

copyright: >
  Copyright &copy; 2024 -> Netomat LLC

# extra:
  # generator: false

extra_css:
  - styles/extra.css

markdown_extensions:
  - attr_list