site_name: "" #Netomat SRL
site_url: https://www.netomat.io/
theme:
  name: material
  logo: assets/netomat_MainLogo.png
  
nav:
  - Home: index.md
  - Blog: https://blog.netomat.io
  - Services:
      - Overview: services/index.md
      - Architecture & Design: services/architecture_design.md
      - Engineering: services/engineering.md
      - Testing: services/testing.md
  - About: about.md
  - Company Details: imprint.md

plugins:
  - search
  - encriptmail:
       placeholderAt: (Q)
       placeholderDot: (P)
  - git-revision-date-localized:
      enable_creation_date: true

copyright: >
  Copyright &copy; 2024 -> Netomat SRL

# extra:
  # generator: false
